services:
  web:
    build: .
    ports:
      - "2000:5000"
    depends_on:
      pull-ollama-model:
        condition: service_completed_successfully

  ollama:
    image: "ollama/ollama"
    ports:
      - "11434:11434"
    healthcheck:
      test: "ollama list || exit 1"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
    volumes:
      - ollama_data:/root/.ollama

  pull-ollama-model:
    image: "curlimages/curl"
    command: >-
      http://ollama:11434/api/pull -d '{"name": "gemma2:2b"}'
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  ollama_data:
